namespace Trading.Monitor.Web.Services;

public sealed record LiveOperationsSnapshot(DateTimeOffset ServerTime, int OpenCount, int HighlightCount, IReadOnlyList<LiveOperationDto> Operations);

public sealed record TradeLinkDto(string Label, string Url);

public sealed record LiveOperationDto(
    string Id,
    string Symbol,
    string Side,
    string SignalType,
    string SignalTypeLabel,
    string SignalTypeDescription,
    bool IsSpotFriendly,
    string Horizon,
    string OperationKind,
    string OperationKindLabel,
    string OriginKind,
    string OriginKindLabel,
    string Status,
    string Action,
    string Conviction,
    string SignalClass,
    bool Highlight,
    int Score,
    DateTimeOffset ObservedAt,
    DateTimeOffset ExpiresAt,
    DateTimeOffset? ExitTime,
    DateTimeOffset EntryAt,
    DateTimeOffset EntryUntil,
    DateTimeOffset ExitBy,
    int SecondsRemaining,
    int PreEntrySecondsRemaining,
    int MaxLifeMinutes,
    decimal LastPrice,
    decimal EntryLower,
    decimal EntryUpper,
    decimal EntryPrice,
    decimal StopLoss,
    decimal TakeProfit1,
    decimal TakeProfit2,
    decimal? ExitPrice,
    decimal Capital,
    decimal EstimatedQuantity,
    decimal EstimatedFees,
    decimal ManagedTargetNetPercent,
    decimal ManagedTargetNetPnL,
    decimal? ManagedTargetExitPrice,
    decimal? MarkPrice,
    decimal FeePercentPerSide,
    decimal EntryFee,
    decimal ExitFee,
    decimal CurrentNetBenefit,
    decimal CurrentNetPercent,
    decimal CurrentTotalObtained,
    string EntryText,
    string ExitText,
    string PotentialText,
    string RiskText,
    string TimeText,
    string PotentialTp1,
    string PotentialTp2,
    string PotentialStop,
    string RealizedText,
    string RealizedPercent,
    decimal? RealizedNetPercent,
    decimal? RealizedTotalObtained,
    string EntryExitText,
    string QuantityText,
    string RealizedFormulaText,
    string ConversionHeadline,
    string EntryConversionText,
    string ExitConversionText,
    string FinalConversionText,
    string CostText,
    string BreakEvenText,
    IReadOnlyList<TradeLinkDto> Links);

public sealed record LiveChartSnapshot(string Symbol, string Interval, DateTimeOffset ServerTime, LiveChartAnalysisDto Analysis, IReadOnlyList<LiveCandleDto> Candles, IReadOnlyList<LiveOperationDto> Operations);

public sealed record LiveCandleDto(DateTimeOffset OpenTime, DateTimeOffset CloseTime, decimal Open, decimal High, decimal Low, decimal Close, decimal Volume);

public sealed record LiveChartAnalysisDto(
    string Horizon,
    string Bias,
    string Action,
    string Side,
    decimal ChangePercent,
    decimal RangePercent,
    string Readout,
    decimal LastPrice,
    decimal EntryLower,
    decimal EntryUpper,
    decimal StopLoss,
    decimal TakeProfit1,
    decimal TakeProfit2,
    decimal EstimatedQuantity,
    decimal PotentialTp1,
    decimal PotentialTp2,
    decimal PotentialStop,
    DateTimeOffset EntryAt,
    DateTimeOffset EntryUntil,
    DateTimeOffset ExitBy,
    string HoldingText);
