<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Trading.Monitor.Application\Trading.Monitor.Application.csproj" />
    <ProjectReference Include="..\Trading.Monitor.Infrastructure\Trading.Monitor.Infrastructure.csproj" />
    <ProjectReference Include="..\Trading.Monitor.Domain\Trading.Monitor.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
