<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-Trading.Monitor.Worker-89733ac4-c1b0-4c0e-9133-6c9b4a8f1b4f</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.File" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Trading.Monitor.Application\Trading.Monitor.Application.csproj" />
		<ProjectReference Include="..\Trading.Monitor.Infrastructure\Trading.Monitor.Infrastructure.csproj" />
		<ProjectReference Include="..\Trading.Monitor.Domain\Trading.Monitor.Domain.csproj" />
	</ItemGroup>
</Project>
